<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
	<AssemblyTitle>Finance.Net</AssemblyTitle>
	<TargetFramework>netstandard2.1</TargetFramework>
	<AssemblyName>Finance.Net</AssemblyName>
	<Nullable>enable</Nullable>
	<RootNamespace>Finance.Net</RootNamespace>
	<AnalysisLevel>latest</AnalysisLevel>
	<EnableNETAnalyzers>True</EnableNETAnalyzers>
	<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	<LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	<PackageId>Finance.NET</PackageId>
	<Version>1.1.15</Version>
	<Authors>Thorsten Alpers</Authors>
	<Owners>Thorsten Alpers</Owners>
	<Description>A .NET library for retrieving real-time and historical financial data from Yahoo Finance and other popular sources.</Description>
	<PackageProjectUrl>https://github.com/thorstenalpers/Finance.NET</PackageProjectUrl>
	<RepositoryUrl>https://github.com/thorstenalpers/Finance.NET</RepositoryUrl>
	<PackageTags>Finance.NET;Yahoo;Yahoo Finance;DataHub;Alpha Vantage;Nasdaq;Xetra;Finance;Trading</PackageTags>
	<Copyright>Copyright 2024-2026</Copyright>
	<RepositoryType>git</RepositoryType>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageIcon>logo.png</PackageIcon>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.5.2" />
    <PackageReference Include="AngleSharp.XPath" Version="2.0.6" />
    <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.29.0.143774">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
	<None Include="./banner.png" Visible="false">
	  <Pack>true</Pack>
	  <PackagePath>/banner.png</PackagePath>
	</None>
	<None Include="./logo.png" Visible="false">
	  <Pack>true</Pack>
	  <PackagePath>/logo.png</PackagePath>
	</None>
	<None Include="../README.md" Visible="false">
	  <Pack>true</Pack>
	  <PackagePath>/README.md</PackagePath>
	</None>
	<None Include="../LICENSE" Visible="false">
	  <Pack>true</Pack>
	  <PackagePath>/LICENSE</PackagePath>
	</None>
  </ItemGroup>
</Project>
